### ISSUE TITLE
[Crash] Firebase crashes on some Windows machines

### ISSUE THREAD

**Issue by Fellhuhn** [firebase/quickstart-unity#1284]
Operating system: Windows
Operating system version: Windows 10 (10.0.19044) 64bit

What steps will reproduce the problem:
- Starting the game (Hnefatafl on Steam) -> Crash

What is the expected result?
- Don't crash...

What happens instead of that?
- It crashes...

The Unity game has been using Firebase for a while now and with the latest update the plugin got upgraded to 9_0_0. Since then some users can't start the game anymore as it crashes right away. The game uses Auth, Database (on desktop) and Messaging (on mobile). The stacktrace:

```
0x00007FFA7ED1A569 (FirebaseCppApp-9_0_0) uWS::HttpSocket<0>::upgrade
0x00007FFA7ED1B8CB (FirebaseCppApp-9_0_0) uWS::HttpSocket<0>::upgrade
0x00007FFA7ED17751 (FirebaseCppApp-9_0_0) uWS::HttpSocket<0>::upgrade
0x00007FFA7ED18320 (FirebaseCppApp-9_0_0) uWS::HttpSocket<0>::upgrade
0x00007FFA7ED18F89 (FirebaseCppApp-9_0_0) uWS::HttpSocket<0>::upgrade
0x00007FFA7ED19279 (FirebaseCppApp-9_0_0) uWS::HttpSocket<0>::upgrade
0x00007FFA7ED15AB3 (FirebaseCppApp-9_0_0) uWS::HttpSocket<0>::upgrade
0x00007FFA7ED08B91 (FirebaseCppApp-9_0_0) uWS::HttpSocket<0>::upgrade
0x00007FFA7EB81544 (FirebaseCppApp-9_0_0) uS::Node::getLoop
0x00007FFA7EB6B387 (FirebaseCppApp-9_0_0) uS::Node::getLoop
0x00007FFA7EB4F8AF (FirebaseCppApp-9_0_0) uS::Node::getLoop
0x00007FFA7EB4FFBB (FirebaseCppApp-9_0_0) uS::Node::getLoop
0x00007FFA7EB48C39 (FirebaseCppApp-9_0_0) uS::Node::getLoop
0x00007FFA7EB3E791 (FirebaseCppApp-9_0_0) uS::Node::getLoop
0x00007FFA7EFAC9F4 (FirebaseCppApp-9_0_0) uWS::HttpSocket<0>::upgrade
0x00007FFA7ED0245F (FirebaseCppApp-9_0_0) uWS::HttpSocket<0>::upgrade
0x00007FFAF4691BB2 (ucrtbase) configthreadlocale
0x00007FFAF57C7034 (KERNEL32) BaseThreadInitThunk
0x00007FFAF6EE2651 (ntdll) RtlUserThreadStart
```

All the app does is using custom auth via our backend and then accessing a realtime database (listening to changes). If those users change back to the old versions everything works fine. The new version also works fine for other users. So there is no consistency here.

**Comment by paulinon** [comment]
Hi @Fellhuhn,

Thanks for reporting this to us. In order to identify what's causing this behavior, could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your implementation?

**Comment by chkuang-g** [comment]
@Fellhuhn

A couple of questions:
- Which SDK version did you upgrade from?
- When it crashes for certain users, did it crash consistently to those users or is it flaky?

Thank you,
Shawn

**Comment by Fellhuhn** [comment]
>     * Which SDK version did you upgrade from?

I updated from firebase_unity_sdk_8.10.1.

>     * When it crashes for certain users, did it crash consistently to those users or is it flaky?

It always crashes, the game doesn't start at all.

As it seems the users are still running Windows 7, which might be the issue. Sadly they are not willing to help in resolving the problem.

**Comment by chkuang-g** [comment]
Thank you for the information.

To summarize, @Fellhuhn saw crashes for Windows standalone build related to websocket handshake upgrade on Windows 7 machine after upgrading Unity SDK from `8.10.1` to `9.0.0`.

It does not seems to have any change in `uWebSocket`, the third-party SDK we use.
Both versions were built from https://github.com/firebase/firebase-unity-sdk.

More investigation may need to be done.

**Comment by chkuang-g** [comment]
There are some change to boringssl from `8.10.1` to `9.0.0`.  This may be the cause.
https://github.com/firebase/firebase-unity-sdk/compare/v8.10.1...v9.0.0

I'll mark this as a bug for now.

**Comment by dconeybe** [comment]
FYI This same crash has been reported against FIrestore as well, with a slightly different stack trace: https://github.com/firebase/firebase-unity-sdk/issues/381

**Comment by deveshbeniwal** [comment]
Do anyone found the solution for this?

**Comment by deveshbeniwal** [comment]
I am not using ANSI characters in my user name but still its crashing at a point where i declare document refrence or collection refrence!
Its crashing at firebaseCoreCpp file socket upgrade

**Comment by deveshbeniwal** [comment]
@dconeybe Got the solution! Unity project is making multiple instances for firestore or realtime database so we have to make it persistant after taking instance. You can declare instance like below - 

        db = FirebaseFirestore.DefaultInstance;
        db.Settings.PersistenceEnabled = false;

NOTE : PersistenceEnabled must be false.
Also this error might thorugh from firebase while we initialize instance. HOPE this will be get solved in next updates

**Comment by dconeybe** [comment]
@deveshbeniwal That's surprising that you fixed this crash by disabling persistence. There _is_ a known issue where only one live Firestore instance can access a Firestore database with persistence enabled, but there is a distinct stack trace when that occurs. This stack trace was related to `uWS`, which has nothing to do with persistence. Maybe it's just a red herring though :shrug: 

@Fellhuhn Could you try disabling persistence to see if it fixes this crash for you? In RTDB call FirebaseDatabase.SetPersistenceEnabled(false).

**Comment by novalain** [comment]
One team member also got this crash and callstack on Windows when upgrading to firebase > 9.0.0 @deveshbeniwal's fix worked great 🎉  hopefully there will be a real fix soon

**Comment by Fellhuhn** [comment]
> @Fellhuhn Could you try disabling persistence to see if it fixes this crash for you? In RTDB call FirebaseDatabase.SetPersistenceEnabled(false).

Updated to 9.2.0 and disabled persistence. It still crashes for that user.

**Comment by Awais6** [comment]
> @dconeybe Got the solution! Unity project is making multiple instances for firestore or realtime database so we have to make it persistant after taking instance. You can declare instance like below -
> 
> ```
>     db = FirebaseFirestore.DefaultInstance;
>     db.Settings.PersistenceEnabled = false;
> ```
> 
> NOTE : PersistenceEnabled must be false. Also this error might thorugh from firebase while we initialize instance. HOPE this will be get solved in next updates

Thanks, It worked, Wasted my 2 hours.

**Comment by sharpgraf** [comment]
> @dconeybe Got the solution! Unity project is making multiple instances for firestore or realtime database so we have to make it persistant after taking instance. You can declare instance like below -
> 
> ```
>     db = FirebaseFirestore.DefaultInstance;
>     db.Settings.PersistenceEnabled = false;
> ```
> 
> NOTE : PersistenceEnabled must be false. Also this error might thorugh from firebase while we initialize instance. HOPE this will be get solved in next updates

works for me ! Thanks !

**Comment by iremguner** [comment]
This issue is still exist for my project. I'm using firebase realtime db 9.5.0 and unity version 2021.3.2f1. 
In the beginning of the preoject I was using PersistenceEnabled = true. Then I changed my code to PersistenceEnabled = false but crash still occurs on Unity Editor. 

Is it possible to have old cache from enabling persistency of database before? I searched on the internet, however I couldn't find a proper solution for cleaning a persistent cache for realtime db. Anyone has a suggestion ?

**Comment by Girildo** [comment]
I encounter this issue on Win 10 win Firebase 11.5 as of October 2023
No special characters in the user's name either.

**Comment by Girildo** [comment]
Anything new on this?
It seems to be machine related. 
I am willing to help nailing down the issue, as I have 2 devices on which I can reproduce this problem-- 100% of the time the app crashes with the exact same stacktrace, apparently at  `uWS::HttpSocket<0>::upgrade`. 

As mentioned in my last comment, the app will work the very first time it is ran and any time * the firestore directory located at "C:\Users\<user>\AppData\Local\firestore" is empty. * 
I can't disable offline persistence because it's a feature I need.

The _exact same executable_ runs on many other windows machines just fine.
Also, the devices where it crashes are a bit older (say 5 to 10 years) but still running 64-bit Windows

Please let me know if I can be of help.

**Comment by felipekieling** [comment]
Aki estava acontecendo sempre o mesmo Stack Trace!!.

========== OUTPUTTING STACK TRACE ==================

0x00007FFB98732F09 (FirebaseCppApp-11_7_0) uWS::HttpSocket<0>::upgrade
0x00007FFB9873426B (FirebaseCppApp-11_7_0) uWS::HttpSocket<0>::upgrade
0x00007FFB987300F1 (FirebaseCppApp-11_7_0) uWS::HttpSocket<0>::upgrade
0x00007FFB98730CC0 (FirebaseCppApp-11_7_0) uWS::HttpSocket<0>::upgrade
0x00007FFB98731929 (FirebaseCppApp-11_7_0) uWS::HttpSocket<0>::upgrade
0x00007FFB98731C19 (FirebaseCppApp-11_7_0) uWS::HttpSocket<0>::upgrade
0x00007FFB9872E453 (FirebaseCppApp-11_7_0) uWS::HttpSocket<0>::upgrade
0x00007FFB98720F01 (FirebaseCppApp-11_7_0) uWS::HttpSocket<0>::upgrade
0x00007FFB9856D144 (FirebaseCppApp-11_7_0) uS::TLS::Context::operator bool
0x00007FFB98556C97 (FirebaseCppApp-11_7_0) uS::TLS::Context::operator bool
0x00007FFB9853A6D1 (FirebaseCppApp-11_7_0) uS::TLS::Context::operator bool
0x00007FFB9853AE96 (FirebaseCppApp-11_7_0) uS::TLS::Context::operator bool
0x00007FFB985333C9 (FirebaseCppApp-11_7_0) uS::TLS::Context::operator bool
0x00007FFB98528E38 (FirebaseCppApp-11_7_0) uS::TLS::Context::operator bool
0x00007FFB984D3A3C (FirebaseCppApp-11_7_0) uS::Socket::freeMessage
0x00007FFB984DCF0F (FirebaseCppApp-11_7_0) uS::Socket::freeMessage
0x00007FFC110F1BB2 (ucrtbase) configthreadlocale
0x00007FFC123B7344 (KERNEL32) BaseThreadInitThunk
0x00007FFC133026B1 (ntdll) RtlUserThreadStart

Estou utilizando FirebaseDatabase, apos utilizar "FirebaseDatabase.DefaultInstance.SetPersistenceEnabled(false);", o crash sumiu ate então!!!
