### ISSUE TITLE
Unable to find command line tool generate_xml_from_google_services_json.exe

### ISSUE THREAD

**Issue by Thaina** [firebase/quickstart-unity#379]
Windows 10 Pro 64 bit 1809
Unity 2018.4.1f1
Firebase 6.1.0

Buildig Android

> Unable to find command line tool Assets/Firebase/Editor/generate_xml_from_google_services_json.exe required for Firebase Android resource generation.
> Assets/Firebase/Editor/generate_xml_from_google_services_json.exe is required to generate the Firebase Android resource file google-services.xml from Assets/GoogleService-Info.plist. Without Firebase Android resources, your app will fail to initialize.
> Assets/Firebase/Editor/generate_xml_from_google_services_json.exe was distributed with each Firebase Unity SDK plugin, was it deleted?
> 

> System.ComponentModel.Win32Exception (0x80004005): ApplicationName='Assets/Firebase/Editor/generate_xml_from_google_services_json.exe', CommandLine='-i "Assets/GoogleService-Info.plist" -l --plist', CurrentDirectory='D:\Users\Admin\Documents\MyProject', Native error= The system cannot find the file specified.

>Native error= The system cannot find the file specified.

The file is exist and the path is correct

![image](https://user-images.githubusercontent.com/1042507/59095014-aa9ff500-8941-11e9-9ad7-2c9ad03ecd75.png)

I try to run the same command in cmd. It seem like it require backslash?

![image](https://user-images.githubusercontent.com/1042507/59095250-33b72c00-8942-11e9-9e7f-ff5c5fcb3cf6.png)

**Comment by ryanmeier** [comment]
Hi @Thaina - thanks for the report, and sorry you're having issues with the Firebase Unity SDK!  We're looking into this issue and hope to be able to have a bugfix release out before too long (likely by the end of the day).  

We'll update you here once the fix is available.

**Comment by stewartmiles** [comment]
This is worked around in https://github.com/googlesamples/unity-jar-resolver/releases/tag/v1.2.116 .  You can import the updated Play Services Resolver plugin over the one shipped with Firebase 6.1.0 to fix this.

As @ryanmeier mentioned a bugfix release (6.1.1) is being prepared that includes this.

**Comment by Thaina** [comment]
@stewartmiles Thank you very much

But just something not relate to this issue. I think github recently has feature to transfer issue between repo isn't it? I think if it possible it would be better than closing and reopening

**Comment by DenizPiri** [comment]
@stewartmiles Using v1.2.116 here, yet the problem still occurs. :/

**Comment by stewartmiles** [comment]
@DenizPiri and @Thaina apologies, yep we discovered we also need to patch Firebase.Editor.dll :( . We'll have that out shortly.

**Comment by stewartmiles** [comment]
Ok the fix is in 6.1.1 https://firebase.google.com/support/release-notes/unity#6.1.1

**Comment by borogove** [comment]
I'm having the same issue with Firebase 6.1.1 and PSR 1.2.121.

**Comment by pranmast** [comment]
Windows 10 Home 32 bit
Unity 5.6.6f2
Firebase 6.4.0

@stewartmiles  I am Having same issue.
pls help.

**Comment by chkuang-g** [comment]
@pranmast 
Could your issue be related to this one?
https://answers.unity.com/questions/1323731/unable-to-list-target-platforms-please-make-sure-t.html

Otherwise, can you provide a bit more information about your issue, ex. error log?

Thank you

**Comment by pranmast** [comment]
@chkuang-g hi, the file google_services_json.exe does not open (this app cant run on this pc error) which is from firebase package 6.4.0 gives could not locate command line tool error in unity just as mentioned above, hence I used the file from 4.0.0 version and it worked. No errors yet, but will check after building apk later. Thanks.

**Comment by stewartmiles** [comment]
@pranmast could you provide a screenshot of the error you're seeing?  I'm assuming you've tried running the tool from the command line window as well?
