### ISSUE TITLE
Fatal Exception: java.lang.Error: FATAL EXCEPTION [UnityMain] libunity.0007f0c0

### ISSUE THREAD

**Issue by gaurangtalwadkar** [firebase/quickstart-unity#818]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.2.21f
  * Firebase Unity SDK version: 6.15.2
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: Crashlytics
  * Other Firebase Components in use: Messaging, Analytics, Dynamic Links
  * Additional SDKs you are using: Facebook, MoPub
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: iOS, Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:
Recently we updated Firebase SDK for unity to 6.15.2. Since the SDK update, getting this crashes reported on Firebase console for Android for armv7 devices. 

```
Fatal Exception: java.lang.Error: FATAL EXCEPTION [UnityMain]
Unity version     : 2019.2.21f1
Device model      : samsung SM-S111DL
Device fingerprint: samsung/a01qtfn/a01q:10/QP1A.190711.020/S111DLUDU2ATF3:user/release-keys
```

```
Caused by java.lang.Error: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0000024c
Build fingerprint: 'samsung/a01qtfn/a01q:10/QP1A.190711.020/S111DLUDU2ATF3:user/release-keys'
Revision: '0'
pid: 31146, tid: 31332, name: UnityMain  >>> air.com.bitrhymes.bingo <<<
    r0 0000024c  r1 b69c6f90  r2 000000c0  r3 b69c6f90
    r4 000000c0  r5 0000024c  r6 0000024c  r7 b6534d2c
    r8 b69c6f90  r9 b6ad2000  sl 00000001  fp 00000000
    ip 000000c0  sp b6534ce0  lr b54be0f3  pc b51580c0  cpsr b6b11c80

       at libunity.0007f0c0()
       at libunity.003e50ef()
       at libunity.004d1915()
       at base.000001f5()
```

Logs as per Firebase console:
```
# Crashlytics - Custom logs
# Application: air.com.bitrhymes.bingo
# Platform: android
# Version: 1.158.0 (1158000)
# Issue: 6e2cd4c66f7a78c52c7b8743b7c1f71d
# Session: 5F855CD00168000168A72C9ED60B7ED8_DNE_0_v2
# Date: Tue Oct 13 2020 13:22:49 GMT+0530 (IST)

0 | Tue Oct 13 2020 13:22:48 GMT+0530 (IST) | screen_view
```

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
We are not able to reproduce the crash

**Comment by chkuang-g** [comment]
Hi @gaurangtalwadkar 

With this limited information, we cannot determine whether if this is related to Crashlytics or even Firebase SDK.
Are you able to reproduce this crash using your app on a local device and captures more information from the log?
We also released `6.16.0` which actually resolves many Android build issues related to Crashlytics.  Should be worth a try and see if that resolve your issue.  **Though most of those are for Unity 2020.  Also be aware of the duplicated package name issue described here.**
https://github.com/firebase/quickstart-unity/issues/806

Otherwise, it would hard for us to take any action about your issue.

Hope this helps!
Shawn

**Comment by gaurangtalwadkar** [comment]
@chkuang-g 
We updated to 6.16.0 but still getting the crash. We were able to reproduce the crash. 
Steps to Reproduce:
1. Launch the app
2. Put app in background once initialisations complete
3. Use some heavy memory hogging apps.
4. Open app through push notification.

Crash log:
```
10-21 14:49:47.514 29564 30526 E CRASH   : 	#00  pc 0011e426  /data/app/air.com.bitrhymes.bingo-QmUbRlp95q4u7BBMh4oejA==/lib/arm/libunity.so (core::StringStorageDefault<char>::assign(char const*, unsigned int)+13)
10-21 14:49:47.514 29564 30526 E CRASH   : 	#01  pc 0074bb43  /data/app/air.com.bitrhymes.bingo-QmUbRlp95q4u7BBMh4oejA==/lib/arm/libunity.so (PlayerSettings::SetAbsoluteURL(core::basic_string<char, core::StringStorageDefault<char> > const&)+22)
10-21 14:49:47.514 29564 30526 E CRASH   : 	#02  pc 00975c61  /data/app/air.com.bitrhymes.bingo-QmUbRlp95q4u7BBMh4oejA==/lib/arm/libunity.so (nativeSetLaunchURL(_JNIEnv*, _jobject*, _jstring*)+72)
10-21 14:49:47.514 29564 30526 E CRASH   : 	#03  pc 0000d519  /apex/com.android.runtime/lib/libart.so
10-21 14:49:47.514 29564 30526 E CRASH   : 	#04  pc 0000d519  /apex/com.android.runtime/lib/libart.so
10-21 14:49:47.514 29564 30526 E CRASH   : 	#05  pc 0000d519  /apex/com.android.runtime/lib/libart.so
10-21 14:49:47.514 29564 30526 E CRASH   : 	#06  pc 0000d519  /apex/com.android.runtime/lib/libart.so
10-21 14:49:47.514 29564 30526 E CRASH   : 	#07  pc 0000d519  /apex/com.android.runtime/lib/libart.so
10-21 14:49:47.514 29564 30526 E CRASH   : 	#08  pc 0000d519  /apex/com.android.runtime/lib/libart.so
10-21 14:49:47.514 29564 30526 E CRASH   : 	#09  pc 0000d519  /apex/com.android.runtime/lib/libart.so
10-21 14:49:47.514 29564 30526 E CRASH   : 	#10  pc 0000d519  /apex/com.android.runtime/lib/libart.so
10-21 14:49:47.514 29564 30526 E CRASH   : 	#11  pc 0000d519  /apex/com.android.runtime/lib/libart.so
10-21 14:49:47.514 29564 30526 E CRASH   : 	#12  pc 0000d519  /apex/com.android.runtime/lib/libart.so
10-21 14:49:47.515 29564 30526 E CRASH   : 	#13  pc 0000d519  /apex/com.android.runtime/lib/libart.so
10-21 14:49:47.515 29564 30526 E CRASH   : 	#14  pc 0000d519  /apex/com.android.runtime/lib/libart.so
10-21 14:49:47.515 29564 30526 E CRASH   : 	#15  pc 0000d519  /apex/com.android.runtime/lib/libart.so
10-21 14:49:47.515 29564 30526 E CRASH   : 	#16  pc 0000d519  /apex/com.android.runtime/lib/libart.so
10-21 14:49:47.515 29564 30526 E CRASH   : 	#17  pc 0000d519  /apex/com.android.runtime/lib/libart.so
10-21 14:49:47.515 29564 30526 E CRASH   : 	#18  pc 0000d519  /apex/com.android.runtime/lib/libart.so
10-21 14:49:47.515 29564 30526 E CRASH   : 	#19  pc 0000d519  /apex/com.android.runtime/lib/libart.so
10-21 14:49:47.515 29564 30526 E CRASH   : 	#20  pc 0000d519  /apex/com.android.runtime/lib/libart.so
10-21 14:49:47.515 29564 30526 E CRASH   : 	#21  pc 0000d519  /apex/com.android.runtime/lib/libart.so
10-21 14:49:47.515 29564 30526 E CRASH   : 	#22  pc 0000d519  /apex/com.android.runtime/lib/libart.so
10-21 14:49:47.515 29564 30526 E CRASH   : 	#23  pc 0000d519  /apex/com.android.runtime/lib/libart.so
10-21 14:49:47.515 29564 30526 E CRASH   : 	#24  pc 0000d519  /apex/com.android.runtime/lib/libart.so
10-21 14:49:47.515 29564 30526 E CRASH   : 	#25  pc 0000d519  /apex/com.android.runtime/lib/libart.so
10-21 14:49:47.515 29564 30526 E CRASH   : 	#26  pc 0000d519  /apex/com.android.runtime/lib/libart.so
10-21 14:49:47.515 29564 30526 E CRASH   : 	#27  pc 0000d519  /apex/com.android.runtime/lib/libart.so
10-21 14:49:47.515 29564 30526 E CRASH   : 	#28  pc 0000d519  /apex/com.android.runtime/lib/libart.so
10-21 14:49:47.515 29564 30526 E CRASH   : 	#29  pc 0000d519  /apex/com.android.runtime/lib/libart.so
10-21 14:49:47.515 29564 30526 E CRASH   : 	#30  pc 0000d519  /apex/com.android.runtime/lib/libart.so
10-21 14:49:47.515 29564 30526 E CRASH   : 	#31  pc 0000d519  /apex/com.android.runtime/lib/libart.so
10-21 14:49:47.515 29564 30526 E CRASH   : 
10-21 14:49:47.515 29564 30526 E CRASH   : memory near r1:
10-21 14:49:47.516 29564 30526 E CRASH   :     b8571cc0 00000000 00000000 b8571be8 000000dc  ..........W.....
10-21 14:49:47.516 29564 30526 E CRASH   :     b8571cd0 00000009 00000181 00000000 ffffffff  ................
10-21 14:49:47.516 29564 30526 E CRASH   :     b8571ce0 35386266 39343734 36323539 682f2f3a  fb8547499526://h
10-21 14:49:47.517 29564 30526 E CRASH   :     b8571cf0 73707474 612f2f3a 2e737070 65636166  ttps://apps.face
10-21 14:49:47.517 29564 30526 E CRASH   :     b8571d00 6b6f6f62 6d6f632e 6765762f 612d7361  book.com/vegas-a
10-21 14:49:47.517 29564 30526 E CRASH   :     b8571d10 702f7070 2e79616c 3f706870 68736168  pp/play.php?hash
10-21 14:49:47.518 29564 30526 E CRASH   :     b8571d20 7266263d 3d64695f 6d697426 74263d65  =&fr_id=&time=&t
10-21 14:49:47.519 29564 30526 E CRASH   :     b8571d30 3d657079 68635050 727a6e69 72617765  ype=PPchinzrewar
10-21 14:49:47.520 29564 30526 E CRASH   :     b8571d40 32527364 31533436 35313036 30343832  dsR264S160152840
10-21 14:49:47.521 29564 30526 E CRASH   :     b8571d50 36314530 30323430 39393736 65746926  0E1604206799&ite
10-21 14:49:47.521 29564 30526 E CRASH   :     b8571d60 64695f6d 7626303d 66697265 70263d79  m_id=0&verify=&p
10-21 14:49:47.522 29564 30526 E CRASH   :     b8571d70 3d707974 79746326 73263d70 79263d65  typ=&ctyp=&se=&y
10-21 14:49:47.522 29564 30526 E CRASH   :     b8571d80 6f6f6861 3d64695f 66657226 7269763d  ahoo_id=&ref=vir
10-21 14:49:47.528 29564 30526 E CRASH   :     b8571d90 75266c61 79745f73 263d6570 003d6372  al&us_type=&rc=.
10-21 14:49:47.528 29564 30526 E CRASH   :     b8571da0 00000000 00000000 b8571cc8 00000128  ..........W.(...
10-21 14:49:47.529 29564 30526 E CRASH   :     b8571db0 00000009 00000219 00000000 ffffffff  ................
10-21 14:49:47.529 29564 30526 E CRASH   : 
10-21 14:49:47.529 29564 30526 E CRASH   : memory near r7:
10-21 14:49:47.530 29564 30526 E CRASH   :     14a01b38 00000001 00010000 00000000 00000000  ................
10-21 14:49:47.532 29564 30526 E CRASH   :     14a01b48 01000001 01000101 14a01b58 00000000  ........X.......
10-21 14:49:47.532 29564 30526 E CRASH   :     14a01b58 14a00658 10000000 00000000 00000000  X...............
10-21 14:49:47.533 29564 30526 E CRASH   :     14a01b68 00000000 00000000 14be89e8 00000000  ................
10-21 14:49:47.534 29564 30526 E CRASH   :     14a01b78 00000000 00000000 00000000 00000000  ................
10-21 14:49:47.535 29564 30526 E CRASH   :     14a01b88 00000000 00000000 00000000 00000000  ................
10-21 14:49:47.536 29564 30526 E CRASH   :     14a01b98 00000000 00000000 00000000 00000000  ................
10-21 14:49:47.536 29564 30526 E CRASH   :     14a01ba8 00000000 00000000 14a01a60 00000000  ........`.......
10-21 14:49:47.537 29564 30526 E CRASH   :     14a01bb8 00000000 00000000 00000000 6f8780c0  ...............o
10-21 14:49:47.538 29564 30526 E CRASH   :     14a01bc8 00000000 00000000 00000000 00000000  ................
10-21 14:49:47.539 29564 30526 E CRASH   :     14a01bd8 00000000 00000000 00000000 00000000  ................
10-21 14:49:47.540 29564 30526 E CRASH   :     14a01be8 00000000 00000000 00000000 14bdcb30  ............0...
10-21 14:49:47.541 29564 30526 E CRASH   :     14a01bf8 00000000 00000000 00000000 00000000  ................
10-21 14:49:47.541 29564 30526 E CRASH   :     14a01c08 00000000 6f8b9ac8 00000000 14bd9218  .......o........
10-21 14:49:47.542 29564 30526 E CRASH   :     14a01c18 00000000 00000000 00000000 00000000  ................
10-21 14:49:47.543 29564 30526 E CRASH   :     14a01c28 00000000 00000000 14cf98c8 00000000  ................
10-21 14:49:47.544 29564 30526 E CRASH   : 
10-21 14:49:47.544 29564 30526 E CRASH   : memory near r8:
10-21 14:49:47.579 29564 30526 E CRASH   :     b8571cc0 00000000 00000000 b8571be8 000000dc  ..........W.....
10-21 14:49:47.581 29564 30494 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
10-21 14:49:47.581 29564 30494 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
10-21 14:49:47.582 29564 30526 E CRASH   :     b8571cd0 00000009 00000181 00000000 ffffffff  ................
10-21 14:49:47.582 29564 30526 E CRASH   :     b8571ce0 35386266 39343734 36323539 682f2f3a  fb8547499526://h
10-21 14:49:47.583 29564 30526 E CRASH   :     b8571cf0 73707474 612f2f3a 2e737070 65636166  ttps://apps.face
10-21 14:49:47.584 29564 30526 E CRASH   :     b8571d00 6b6f6f62 6d6f632e 6765762f 612d7361  book.com/vegas-a
10-21 14:49:47.585 29564 30526 E CRASH   :     b8571d10 702f7070 2e79616c 3f706870 68736168  pp/play.php?hash
10-21 14:49:47.586 29564 30526 E CRASH   :     b8571d20 7266263d 3d64695f 6d697426 74263d65  =&fr_id=&time=&t
10-21 14:49:47.586 29564 30526 E CRASH   :     b8571d30 3d657079 68635050 727a6e69 72617765  ype=PPchinzrewar
10-21 14:49:47.587 29564 30526 E CRASH   :     b8571d40 32527364 31533436 35313036 30343832  dsR264S160152840
10-21 14:49:47.587 29564 30526 E CRASH   :     b8571d50 36314530 30323430 39393736 65746926  0E1604206799&ite
10-21 14:49:47.588 29564 30526 E CRASH   :     b8571d60 64695f6d 7626303d 66697265 70263d79  m_id=0&verify=&p
10-21 14:49:47.589 29564 30526 E CRASH   :     b8571d70 3d707974 79746326 73263d70 79263d65  typ=&ctyp=&se=&y
10-21 14:49:47.589 29564 30526 E CRASH   :     b8571d80 6f6f6861 3d64695f 66657226 7269763d  ahoo_id=&ref=vir
10-21 14:49:47.590 29564 30526 E CRASH   :     b8571d90 75266c61 79745f73 263d6570 003d6372  al&us_type=&rc=.
10-21 14:49:47.591 29564 30526 E CRASH   :     b8571da0 00000000 00000000 b8571cc8 00000128  ..........W.(...
10-21 14:49:47.591 29564 30526 E CRASH   :     b8571db0 00000009 00000219 00000000 ffffffff  ................
10-21 14:49:47.591 29564 30526 E CRASH   : 
10-21 14:49:47.591 29564 30526 E CRASH   : memory near r9:
10-21 14:49:47.592 29564 30526 E CRASH   :     b88f33e0 00000000 40000000 00217bb0 00002003  .......@.{!.. ..
10-21 14:49:47.608  3606  3668 I display : HWC setVsyncEnabled = 0
10-21 14:49:47.613 29564 30526 E CRASH   :     b88f33f0 00000000 00000000 00000000 00000000  ................
10-21 14:49:47.613 29564 30526 E CRASH   :     b88f3400 005c0000 00000000 00000000 00000024  ..\.........$...
10-21 14:49:47.613 29564 30526 E CRASH   :     b88f3410 0000773e 00000000 00000000 00000000  >w..............
10-21 14:49:47.614 29564 30526 E CRASH   :     b88f3420 00000000 00000000 00000000 00000000  ................
10-21 14:49:47.614 29564 30526 E CRASH   :     b88f3430 00000000 00000001 00000000 00000001  ................
10-21 14:49:47.623 29564 30526 E CRASH   :     b88f3440 00000001 00000000 00000000 00000000  ................
10-21 14:49:47.624 29564 30526 E CRASH   :     b88f3450 00000001 00002001 00000000 00000000  ..... ..........
10-21 14:49:47.624 29564 30526 E CRASH   :     b88f3460 00000000 00000000 00000000 00000000  ................
10-21 14:49:47.625 29564 30526 E CRASH   :     b88f3470 00000000 00000000 00000000 00000000  ................
10-21 14:49:47.626 29564 30526 E CRASH   :     b88f3480 00000000 00000000 00000001 00000000  ................
10-21 14:49:47.627 29564 30526 E CRASH   :     b88f3490 0000168a 00000000 e0540070 00000000  ........p.T.....
10-21 14:49:47.627 29564 30526 E CRASH   :     b88f34a0 b587e000 b597e4e1 b597e640 00000000  ........@.......
10-21 14:49:47.628 29564 30526 E CRASH   :     b88f34b0 00000000 ea164380 00000000 00000000  .....C..........
10-21 14:49:47.629 29564 30526 E CRASH   :     b88f34c0 14c760d0 00000000 b587c000 00104230  .`..........0B..
10-21 14:49:47.629 29564 30526 E CRASH   :     b88f34d0 00000000 00000000 00000000 b597e4e4  ................
10-21 14:49:47.630 29564 30526 E CRASH   : 
10-21 14:49:47.630 29564 30526 E CRASH   : memory near sl:
10-21 14:49:47.630 29564 30526 E CRASH   :     b597e4d0 00000000 00000000 00000000 00000000  ................
10-21 14:49:47.631 29564 30526 E CRASH   :     b597e4e0 d59a7860 00000000 00000002 14a01b58  `x..........X...
10-21 14:49:47.632 29564 30526 E CRASH   :     b597e4f0 14cc97e8 14c80260 b597e5d0 b88f3400  ....`........4..
10-21 14:49:47.652 29564 30526 E CRASH   :     b597e500 b597e668 e881b260 b597ed40 00000001  h...`...@.......
10-21 14:49:47.652 29564 30526 E CRASH   :     b597e510 00000001 e5543467 b597ed40 6f516500  ....g4T.@....eQo
10-21 14:49:47.652 29564 30526 E CRASH   :     b597e520 b597e730 6f660340 00000000 00000000  0...@.fo........
10-21 14:49:47.652 29564 30526 E CRASH   :     b597e530 ea245180 d5f37920 14a01b58 14cc97e8  .Q$. y..X.......
10-21 14:49:47.653 29564 30526 E CRASH   :     b597e540 16f1b07d 00000002 00000003 14a01b58  }...........X...
10-21 14:49:47.654 29564 30526 E CRASH   :     b597e550 00000001 b597e5e8 b597e56c e540ebc7  ........l.....@.
10-21 14:49:47.654 29564 30526 E CRASH   :     b597e560 00000000 14a01b58 14cc97e8 b929242c  ....X.......,$).
10-21 14:49:47.654 29564 30526 E CRASH   :     b597e570 00000002 00000003 14a01b58 e881b260  ........X...`...
10-21 14:49:47.654 29564 30526 E CRASH   :     b597e580 b597e5a8 b597e5e8 00000000 e57659db  .............Yv.
10-21 14:49:47.655 29564 30526 E CRASH   :     b597e590 b597ed40 00000000 b597e5e8 b597e5a8  @...............
10-21 14:49:47.655 29564 30526 E CRASH   :     b597e5a0 00000008 b88f3400 b597e5d0 b88f3400  .....4.......4..
10-21 14:49:47.655 29564 30526 E CRASH   :     b597e5b0 b597e668 e881b260 b597ed40 00000001  h...`...@.......
10-21 14:49:47.655 29564 30526 E CRASH   :     b597e5c0 00000001 e5543467 b597ed40 6f516500  ....g4T.@....eQo
10-21 14:49:47.655 29564 30526 E CRASH   : 
10-21 14:49:47.655 29564 30526 E CRASH   : memory near fp:
10-21 14:49:47.655 29564 30526 E CRASH   :     b88f33e0 00000000 40000000 00217bb0 00002003  .......@.{!.. ..
10-21 14:49:47.656 29564 30526 E CRASH   :     b88f33f0 00000000 00000000 00000000 00000000  ................
10-21 14:49:47.656 29564 30526 E CRASH   :     b88f3400 005c0000 00000000 00000000 00000024  ..\.........$...
10-21 14:49:47.656 29564 30526 E CRASH   :     b88f3410 0000773e 00000000 00000000 00000000  >w..............
10-21 14:49:47.656 29564 30526 E CRASH   :     b88f3420 00000000 00000000 00000000 00000000  ................
10-21 14:49:47.656 29564 30526 E CRASH   :     b88f3430 00000000 00000000 00000000 00000001  ................
10-21 14:49:47.656 29564 30526 E CRASH   :     b88f3440 00000001 00000000 00000000 00000000  ................
10-21 14:49:47.656 29564 30526 E CRASH   :     b88f3450 00000001 00002001 00000000 00000000  ..... ..........
10-21 14:49:47.656 29564 30526 E CRASH   :     b88f3460 00000000 00000000 00000000 00000000  ................
10-21 14:49:47.657 29564 30526 E CRASH   :     b88f3470 00000000 00000000 00000000 00000000  ................
10-21 14:49:47.657 29564 30526 E CRASH   :     b88f3480 00000000 00000000 00000001 00000000  ................
10-21 14:49:47.657 29564 30526 E CRASH   :     b88f3490 0000168a 00000000 e0540070 00000000  ........p.T.....
10-21 14:49:47.657 29564 30526 E CRASH   :     b88f34a0 b587e000 b597e4e1 b597e640 00000000  ........@.......
10-21 14:49:47.657 29564 30526 E CRASH   :     b88f34b0 00000000 ea164380 00000000 00000000  .....C..........
10-21 14:49:47.657 29564 30526 E CRASH   :     b88f34c0 14c760d0 00000000 b587c000 00104230  .`..........0B..
10-21 14:49:47.658 29564 30526 E CRASH   :     b88f34d0 00000000 00000000 00000000 b597e4e4  ................
10-21 14:49:47.658 29564 30526 E CRASH   : 
10-21 14:49:47.658 29564 30526 E CRASH   : memory near sp:
10-21 14:49:47.658 29564 30526 E CRASH   :     b597e418 b597e4b0 00000010 000000c0 b41e64c0  .............d..
10-21 14:49:47.658 29564 30526 E CRASH   :     b597e428 00000127 b597e4f0 b88f3400 b4566179  '........4..yaV.
10-21 14:49:47.658 29564 30526 E CRASH   :     b597e438 00000000 b41e64c0 b597e498 b597e498  .....d..........
10-21 14:49:47.658 29564 30526 E CRASH   :     b597e448 00000000 14a01b58 00000001 b4813b47  ....X.......G;..
10-21 14:49:47.658 29564 30526 E CRASH   :     b597e458 b8571ce0 b41e6499 b41e64c0 00000127  ..W..d...d..'...
10-21 14:49:47.658 29564 30526 E CRASH   :     b597e468 b8571c00 b597e498 00000000 14a01b58  ..W.........X...
10-21 14:49:47.659 29564 30526 E CRASH   :     b597e478 00000001 16f1b07d b8571820 b597e498  ....}... .W.....
10-21 14:49:47.659 29564 30526 E CRASH   :     b597e488 14a01b58 b4a3dc65 b597ed40 b8571c00  X...e...@.....W.
10-21 14:49:47.659 29564 30526 E CRASH   :     b597e498 b8571ce0 000000bf 00000004 b88f3400  ..W..........4..
10-21 14:49:47.664 29564 30526 E CRASH   :     b597e4a8 b597e560 000000bf 00000000 ffffffff  `...............
10-21 14:49:47.665 29564 30526 E CRASH   :     b597e4b8 00000049 16f1b07d d59a7860 00000002  I...}...`x......
10-21 14:49:47.665 29564 30526 E CRASH   :     b597e4c8 00000003 e541351b 00000000 00000000  .....5A.........
10-21 14:49:47.666 29564 30526 E CRASH   :     b597e4d8 00000000 00000000 d59a7860 00000000  ........`x......
10-21 14:49:47.666 29564 30526 E CRASH   :     b597e4e8 00000002 14a01b58 14cc97e8 14c80260  ....X.......`...
10-21 14:49:47.666 29564 30526 E CRASH   :     b597e4f8 b597e5d0 b88f3400 b597e668 e881b260  .....4..h...`...
10-21 14:49:47.667 29564 30526 E CRASH   :     b597e508 b597ed40 00000001 00000001 e5543467  @...........g4T.
10-21 14:49:47.667 29564 30526 E CRASH   : 
10-21 14:49:47.667 29564 30526 E CRASH   : code around pc:
10-21 14:49:47.668 29564 30526 E CRASH   :     b41e6404 4602ee3a 46214628 f804f000 bd704628  :..F(F!F....(Fp.
10-21 14:49:47.671 29564 30526 E CRASH   :     b41e6414 0142335a 41f0e92d 4606b082 46354614  Z3B.-..A...F.F5F
10-21 14:49:47.672 29564 30526 E CRASH   :     b41e6424 f8554688 28000b04 bf084607 4547462f  .FU....(.F../FGE
10-21 14:49:47.673 29564 30526 E CRASH   :     b41e6434 6971d803 4542187a 6871d834 460ab161  ..qiz.BE4.qha..F
10-21 14:49:47.674 29564 30526 E CRASH   :     b41e6444 bf082800 42a2220f b130d21f f106b129  .(...".B..0.)...
10-21 14:49:47.675 29564 30526 E CRASH   :     b41e6454 f37f0118 e000ff46 2c10b310 f240d30d  ....F......,..@.
10-21 14:49:47.676 29564 30526 E CRASH   :     b41e6464 a1161027 1000e9cd f1061c60 21100218  '.......`......!
10-21 14:49:47.676 29564 30526 E CRASH   :     b41e6474 f37f2300 4621fe6d 2000e001 e9c62100  .#..m.!F... .!..
10-21 14:49:47.677 29564 30526 E CRASH   :     b41e6484 28000100 4605bf18 4638462f 46224641  ...(...F/F8FAF"F
10-21 14:49:47.678 29564 30526 E CRASH   :     b41e6494 edf6f75c 55382000 b0026174 81f0e8bd  \.... 8Uta......
10-21 14:49:47.678 29564 30526 E CRASH   :     b41e64a4 e7d0220f bf3842a1 4547460c 4638d0f2  ."...B8..FGE..8F
10-21 14:49:47.679 29564 30526 E CRASH   :     b41e64b4 46224641 edeaf75c bf00e7ec 75522f2e  AF"F\......../Ru
10-21 14:49:47.680 29564 30526 E CRASH   :     b41e64c4 6d69746e 6f432f65 432f6572 61746e6f  ntime/Core/Conta
10-21 14:49:47.681 29564 30526 E CRASH   :     b41e64d4 72656e69 74532f73 676e6972 726f7453  iners/StringStor
10-21 14:49:47.682 29564 30526 E CRASH   :     b41e64e4 44656761 75616665 682e746c 00000000  ageDefault.h....
10-21 14:49:47.683 29564 30526 E CRASH   :     b41e64f4 41f0e92d 3400e9d1 68104680 10b61ae6  -..A...4.F.h....
10-21 14:49:47.683 29564 30526 E CRASH   : 
10-21 14:49:47.683 29564 30526 E CRASH   : code around lr:
10-21 14:49:47.684 29564 30526 E CRASH   :     b4813b24 f8904770 477001dd b08ab5b0 4916460c  pG....pG.....F.I
10-21 14:49:47.684 29564 30526 E CRASH   :     b4813b34 7029f500 68094479 91096809 f5d24621  ..)pyD.h.h..!F..
10-21 14:49:47.684 29564 30526 E CRASH   :     b4813b44 f1bcf5ab b1a0fe4d 0b04f854 2800466d  ....M...T...mF.(
10-21 14:49:47.684 29564 30526 E CRASH   :     b4813b54 4604bf18 46214628 f442f5d2 f5db2100  ...F(F!F..B..!..
10-21 14:49:47.684 29564 30526 E CRASH   :     b4813b64 9800f133 9901b128 f105b119 f5520118  3...(.........R.
10-21 14:49:47.685 29564 30526 E CRASH   :     b4813b74 4806fbb8 44789909 68006800 bf041a40  ...H..xD.h.h@...
10-21 14:49:47.685 29564 30526 E CRASH   :     b4813b84 bdb0b00a e26af52f 00df5bec 00df5baa  ..../.j..[...[..
10-21 14:49:47.685 29564 30526 E CRASH   :     b4813b94 490db580 44794b0e e030f8df c034f8df  ...I.KyD..0...4.
10-21 14:49:47.685 29564 30526 E CRASH   :     b4813ba4 4a0d447b 610844fe 447a2000 44fc604a  {D.J.D.a. zDJ`.D
10-21 14:49:47.685 29564 30526 E CRASH   :     b4813bb4 e30de9c1 c03cf8c1 000ae9c1 e8bd4608  ......<......F..
10-21 14:49:47.685 29564 30526 E CRASH   :     b4813bc4 f5754080 bf00bb01 00de3012 fffffcd5  .@u......0......
10-21 14:49:47.685 29564 30526 E CRASH   :     b4813bd4 fffffdf9 00000cd3 0000002f b08ab570  ......../...p...
10-21 14:49:47.686 29564 30526 E CRASH   :     b4813be4 e03cf8df f8df461c 4613c03c 460a44fe  ..<..F..<..F.D.F
10-21 14:49:47.686 29564 30526 E CRASH   :     b4813bf4 460144fc 20002604 6e00e9cd e9cd250f  .D.F.&. ...n.%..
10-21 14:49:47.686 29564 30526 E CRASH   :     b4813c04 a8060c02 f0009504 ad06fdf9 9400cd2e  ................
10-21 14:49:47.686 29564 30526 E CRASH   :     b4813c14 f7ff4628 f554fc55 4628f8c5 bd70b00a  (F..U.T...(F..p.
--------- beginning of crash
10-21 14:49:47.699 29564 30526 E AndroidRuntime: FATAL EXCEPTION: UnityMain
10-21 14:49:47.699 29564 30526 E AndroidRuntime: Process: air.com.bitrhymes.bingo, PID: 29564
10-21 14:49:47.699 29564 30526 E AndroidRuntime: java.lang.Error: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 000002a4
10-21 14:49:47.699 29564 30526 E AndroidRuntime: Build fingerprint: 'samsung/gta3xlinu/gta3xl:10/QP1A.190711.020/T515XXU5BTI1:user/release-keys'
10-21 14:49:47.699 29564 30526 E AndroidRuntime: Revision: '4'
10-21 14:49:47.699 29564 30526 E AndroidRuntime: pid: 29564, tid: 30526, name: UnityMain  >>> air.com.bitrhymes.bingo <<<
10-21 14:49:47.699 29564 30526 E AndroidRuntime:     r0 000002a4  r1 b8571ce0  r2 000000bf  r3 00000000
10-21 14:49:47.699 29564 30526 E AndroidRuntime:     r4 000000bf  r5 000002a4  r6 000002a4  r7 14a01b58
10-21 14:49:47.699 29564 30526 E AndroidRuntime:     r8 b8571ce0  r9 b88f3400  sl b597e4f0  fp b88f3400
10-21 14:49:47.699 29564 30526 E AndroidRuntime:     ip 00000063  sp b597e438  lr b4813b47  pc b41e6426  cpsr b599c900
10-21 14:49:47.699 29564 30526 E AndroidRuntime: 
10-21 14:49:47.699 29564 30526 E AndroidRuntime: 	at libunity.core::StringStorageDefault<char>::assign(char const*, unsigned int)(StringStorageDefault:13)
10-21 14:49:47.699 29564 30526 E AndroidRuntime: 	at libunity.PlayerSettings::SetAbsoluteURL(core::basic_string<char, core::StringStorageDefault<char> > const&)(SetAbsoluteURL:22)
10-21 14:49:47.699 29564 30526 E AndroidRuntime: 	at libunity.nativeSetLaunchURL(_JNIEnv*, _jobject*, _jstring*)(nativeSetLaunchURL:72)
10-21 14:49:47.699 29564 30526 E AndroidRuntime: 	at libart.0000d519(Native Method)
10-21 14:49:47.699 29564 30526 E AndroidRuntime: 	at libart.0000d519(Native Method)
10-21 14:49:47.699 29564 30526 E AndroidRuntime: 	at libart.0000d519(Native Method)
10-21 14:49:47.699 29564 30526 E AndroidRuntime: 	at libart.0000d519(Native Method)
10-21 14:49:47.699 29564 30526 E AndroidRuntime: 	at libart.0000d519(Native Method)
10-21 14:49:47.699 29564 30526 E AndroidRuntime: 	at libart.0000d519(Native Method)
10-21 14:49:47.699 29564 30526 E AndroidRuntime: 	at libart.0000d519(Native Method)
10-21 14:49:47.699 29564 30526 E AndroidRuntime: 	at libart.0000d519(Native Method)
10-21 14:49:47.699 29564 30526 E AndroidRuntime: 	at libart.0000d519(Native Method)
10-21 14:49:47.699 29564 30526 E AndroidRuntime: 	at libart.0000d519(Native Method)
10-21 14:49:47.699 29564 30526 E AndroidRuntime: 	at libart.0000d519(Native Method)
10-21 14:49:47.699 29564 30526 E AndroidRuntime: 	at libart.0000d519(Native Method)
10-21 14:49:47.699 29564 30526 E AndroidRuntime: 	at libart.0000d519(Native Method)
10-21 14:49:47.699 29564 30526 E AndroidRuntime: 	at libart.0000d519(Native Method)
10-21 14:49:47.699 29564 30526 E AndroidRuntime: 	at libart.0000d519(Native Method)
10-21 14:49:47.699 29564 30526 E AndroidRuntime: 	at libart.0000d519(Native Method)
10-21 14:49:47.699 29564 30526 E AndroidRuntime: 	at libart.0000d519(Native Method)
10-21 14:49:47.699 29564 30526 E AndroidRuntime: 	at libart.0000d519(Native Method)
10-21 14:49:47.699 29564 30526 E AndroidRuntime: 	at libart.0000d519(Native Method)
10-21 14:49:47.699 29564 30526 E AndroidRuntime: 	at libart.0000d519(Native Method)
10-21 14:49:47.699 29564 30526 E AndroidRuntime: 	at libart.0000d519(Native Method)
10-21 14:49:47.699 29564 30526 E AndroidRuntime: 	at libart.0000d519(Native Method)
10-21 14:49:47.699 29564 30526 E AndroidRuntime: 	at libart.0000d519(Native Method)
10-21 14:49:47.699 29564 30526 E AndroidRuntime: 	at libart.0000d519(Native Method)
10-21 14:49:47.699 29564 30526 E AndroidRuntime: 	at libart.0000d519(Native Method)
10-21 14:49:47.699 29564 30526 E AndroidRuntime: 	at libart.0000d519(Native Method)
10-21 14:49:47.699 29564 30526 E AndroidRuntime: 	at libart.0000d519(Native Method)
10-21 14:49:47.699 29564 30526 E AndroidRuntime: 	at libart.0000d519(Native Method)
10-21 14:49:47.699 29564 30526 E AndroidRuntime: 	at libart.0000d519(Native Method)
10-21 14:49:47.736  4058 30534 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
10-21 14:49:47.740  4058  7039 D Debug   : !@DumpState : SHIP
10-21 14:49:47.740  4058  7039 D Debug   : !@DumpState : debug level:0x4f4c
10-21 14:49:47.740  4058  7039 D Debug   : !@Dumpstate : Finally, system will skip dumpstate
10-21 14:49:47.741  4058  7039 W ActivityManager: crash : air.com.bitrhymes.bingo,0
10-21 14:49:47.747  4058  7039 W ActivityTaskManager:   Force finishing activity air.com.bitrhymes.bingo/com.google.firebase.MessagingUnityPlayerActivity
10-21 14:49:47.752 29564 29564 I Unity   : onPause
10-21 14:49:47.778 29564 30526 I Process : Sending signal. PID: 29564 SIG: 9
10-21 14:49:47.786 26989 26989 I BatteryReceiver: Received : com.samsung.android.sm.ACTION_ERROR
```

**Comment by patm1987** [comment]
To address @chkuang-g 's first comment - 6.16.1 does address further Crashlytics issues. Trying that could help.

With that said, a few things to try. First, if you _can_ get this [reproduced in the Quickstart](https://github.com/firebase/quickstart-unity/tree/master/messaging/testapp), it'll help us find and track the bug faster.

You mentioned that you need to put the phone under heavy load. To make this test more reliable, does the crash happen if you set your phone to exit activities when they enter the background? This is a developer option in Android:
![image](https://user-images.githubusercontent.com/1111611/98424749-fc294380-204f-11eb-94df-f0c436b4f880.png)
